#!/bin/bash
set -euo pipefail

# XXX: Prevents `set -u` from breaking out of the checks if this
#      variable is not defined
export DEPLOY_MASTER_CLUSTER="${DEPLOY_MASTER_CLUSTER:-false}"

if [[ $PLATFORM == openshift ]]; then
  oc login -u $OSHIFT_CLUSTER_ADMIN_USERNAME
fi

./0_check_dependencies.sh

./stop

./1_prepare_conjur_namespace.sh
./2_prepare_docker_images.sh

if [[ "${DEPLOY_MASTER_CLUSTER}" = "true" ]]; then
  ./3_deploy_conjur_master_cluster.sh
fi

./4_deploy_conjur_followers.sh

if [[ "${DEPLOY_MASTER_CLUSTER}" = "true" ]]; then
  ./5_create_load_balancer.sh
  ./6_configure_master.sh
  ./7_configure_standbys.sh
fi

./8_configure_followers.sh
./9_print_cluster_info.sh
