#!/bin/bash
set -euo pipefail

. utils.sh

if [[ $PLATFORM == openshift ]]; then
  export OPENSHIFT_USERNAME="${OPENSHIFT_USERNAME:-$OSHIFT_CLUSTER_ADMIN_USERNAME}"
  oc_login
fi

set_namespace default

if has_namespace $CONJUR_NAMESPACE_NAME; then
  if [[ "$PLATFORM" == "openshift" && "$OPENSHIFT_VERSION" == "4.3" ]]; then
    # Workaround for https://bugzilla.redhat.com/show_bug.cgi?id=1798282
    for svc in `$cli get svc -n "$CONJUR_NAMESPACE_NAME" -o name`; do
      echo "Deleting finalizers from Kubernetes service $svc"
      "$cli" patch "$svc" \
          --namespace "$CONJUR_NAMESPACE_NAME" \
          --type=json \
          --patch='[{"op":"replace","path":"/metadata/finalizers","value":[]}]'
    done
  fi

  $cli delete namespace $CONJUR_NAMESPACE_NAME

  printf "Waiting for $CONJUR_NAMESPACE_NAME namespace deletion to complete"

  while has_namespace "$CONJUR_NAMESPACE_NAME"; do
    printf "."
    sleep 5
  done

  echo ""
fi

echo "Deleting cluster role"
$cli delete --ignore-not-found clusterrole conjur-authenticator-$CONJUR_NAMESPACE_NAME

echo "Conjur environment purged."
