#!/bin/bash
set -euo pipefail

./0_check_dependencies.sh

./stop

./1_create_conjur_namespace.sh
./2_build_and_push_containers.sh
./3_deploy_conjur_cluster.sh
./4_configure_master.sh
./5_print_config.sh
