#!/bin/bash
set -eou pipefail

. utils.sh

set_context default

if has_context $CONJUR_CONTEXT_NAME; then
  kubectl delete namespace $CONJUR_CONTEXT_NAME

  printf "Waiting for $CONJUR_CONTEXT_NAME context deletion to complete"

  while : ; do
    printf "..."
    
    if has_context "$CONJUR_CONTEXT_NAME"; then
      sleep 5
    else
      break
    fi
  done

  echo ""
fi

echo "Conjur environment purged."
