#!/bin/bash
set -eo pipefail

# This script updates the HAProxy configuration for currently running Conjur
# pods and restarts the proxy daemon.

. ./utils.sh

declare template_file="./haproxy/haproxy.template.cfg"
declare destination_file="./haproxy/$CONJUR_NAMESPACE_NAME/haproxy.cfg"

main() {
  haproxy_pod_name=$1

  # Create dir w/ guid from namespace name for parallel CI execution
  mkdir -p "./haproxy/$CONJUR_NAMESPACE_NAME"
  
  echo "# This file is generated by $0 in $(pwd)." > $destination_file
  cp $template_file $destination_file

  append_frontend http 443
  append_frontend pg 5432
  append_frontend ldap 636
  append_frontend syslog 1999
  
  append_backend http 443
  append_backend pg 5432
  append_backend ldap 636
  append_backend syslog 1999

  copy_file_to_container "$destination_file" "/usr/local/etc/haproxy/haproxy.cfg" "$haproxy_pod_name"
  $cli exec $haproxy_pod_name -- kill -s HUP 1  # haproxy runs as PID 1, see Reloading Config here: https://hub.docker.com/_/haproxy/

  rm -rf "./haproxy/$CONJUR_NAMESPACE_NAME"
}

append_frontend() {
  local name=$1; shift
  local port=$1; shift

  cat <<CONFIG >> $destination_file

# $name frontend info 
# Generated by $0 in $(pwd)
frontend f_conjur_master_$name
	mode tcp
	bind *:$port
	default_backend b_conjur_master_$name
CONFIG
}

append_backend() {
  local name=$1; shift
  local port=$1; shift

  cat <<CONFIG >> $destination_file

# $name backend info 
# Generated by $0 in $(pwd)
backend b_conjur_master_$name
	mode tcp
	balance static-rr
	option external-check
	default-server inter 5s fall 3 rise 2
	external-check path "/usr/bin:/usr/local/bin"
	external-check command "/root/conjur-health-check.sh"
CONFIG

  pod_list=$($cli get pods -l app=conjur-node --no-headers | awk '{print $1}')
  
  for pname in $pod_list; do
    pod_ip=$($cli describe pod $pname | grep "IP:" | awk '{print $2}')
    echo -e '\t'server $pname $pod_ip:$port check >> $destination_file
  done
}

main "$@"
