---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: conjur-authenticator-role-binding-{{ CONJUR_NAMESPACE_NAME }}
subjects:
  - kind: ServiceAccount
    name: conjur-cluster
    namespace: {{ CONJUR_NAMESPACE_NAME }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: conjur-authenticator-{{ CONJUR_NAMESPACE_NAME }}

