---
apiVersion: rbac.authorization.k8s.io/v1beta1 # TODO: change this to match your k8s version
kind: ClusterRole
metadata:
  name: conjur-authenticator
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create", "get"]
