---
apiVersion: v1
kind: Service
metadata:
  name: conjur-master
  labels:
    app: haproxy-conjur-master
spec:
  ports:
  - port: 443
    name: https
#    nodePort: 30443
  - port: 636
    name: ldaps
  - port: 5432
    name: pg-main
  selector:
    app: haproxy-conjur-master
  type: LoadBalancer
---
apiVersion: v1
kind: Pod
metadata:
  name: haproxy-conjur-master
  labels:
    app: haproxy-conjur-master
spec:
  serviceAccountName: conjur-cluster
  containers:
  - name: haproxy
    image: {{ DOCKER_IMAGE }}
    imagePullPolicy: {{ IMAGE_PULL_POLICY }}
    ports:
    - containerPort: 443
      name: https
    - containerPort: 636
      name: ldaps
    - containerPort: 5432
      name: pg-main
    - containerPort: 5433
      name: pg-audit
  imagePullSecrets:
    - name: dockerpullsecret
