#!/bin/bash 
set -eou pipefail

. utils.sh

set_namespace default

if has_namespace $TEST_APP_NAMESPACE_NAME; then
  kubectl delete namespace $TEST_APP_NAMESPACE_NAME

  printf "Waiting for $TEST_APP_NAMESPACE_NAME namespace deletion to complete"

  while : ; do
    printf "..."
    
    if has_namespace "$TEST_APP_NAMESPACE_NAME"; then
      sleep 5
    else
      break
    fi
  done

  echo ""
fi

echo "Test app environment purged."
