---
apiVersion: v1
kind: Service
metadata:
  name: conjur-follower
  labels:
    app: conjur-follower
spec:
  ports:
  - port: 443
    name: https
  - port: 636
    name: ldaps
  selector:
    app: conjur-follower

---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: conjur-follower
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: conjur-follower
        name: conjur-follower
        role: follower
    spec:
<<<<<<< HEAD
      serviceAccountName: conjur-cluster
=======
>>>>>>> master
      containers:
      - name: conjur-appliance
        image: {{ CONJUR_APPLIANCE_IMAGE }}
        imagePullPolicy: Always
        env:
          - name: CONJUR_AUTHENTICATORS
            value: authn-k8s/{{ AUTHENTICATOR_ID }}
        ports:
        - containerPort: 443
          name: https
        - containerPort: 636
          name: ldaps
        - containerPort: 5432
          name: pg-main
        - containerPort: 5433
          name: pg-audit
