---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: conjur-cluster
  name: conjur-cluster
spec:
  replicas: 3
  selector:
    matchLabels:
      app: conjur-node
  template:
    metadata:
      labels:
        app: conjur-node
        name: conjur-node
        role: unset # set to master or standby when configured
    spec:
      serviceAccountName: conjur-cluster
      containers:
      - name: conjur-appliance
        image: {{ CONJUR_APPLIANCE_IMAGE }}
        imagePullPolicy: {{ IMAGE_PULL_POLICY }}
        ports:
        - containerPort: 443
          name: https
        - containerPort: 636
          name: ldaps
        - containerPort: 5432
          name: pg-main
        - containerPort: 5433
          name: pg-audit
        - containerPort: 1999
          name: syslog-audit
        readinessProbe:
          httpGet:
            path: /health
            port: https
            scheme: HTTPS
        securityContext:
          capabilities:
            add: ["AUDIT_WRITE"]
          allowPrivilegeEscalation: false
        resources:
          requests:
            cpu: 1
            memory: 1.5Gi
          limits:
            cpu: 2
            memory: 4Gi